name: testdocs
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install requirements
      run: |
        sudo apt-get update -y
        apt show enchant
        sudo apt-get install -y build-essential enchant libenchant-dev libenchant-voikko
        python -m pip install --upgrade wheel
        python -m pip install --upgrade pip 
        python -m pip install --upgrade tox
    
    - name: Log system information
      run: |
        test -r /etc/os-release && sh -c '. /etc/os-release && echo "OS: $PRETTY_NAME"'
        python --version
        python -c "print('\nENVIRONMENT VARIABLES\n=====================\n')"
        python -c "import os; [print(f'{k}={v}') for k, v in os.environ.items()]"
    
    - name: Run tests (English)
      run: |
        tox -e testdocs

    # Disable until the french build also succeeds
    # - name: Run tests (French)
    #   run: |
    #     tox -e testdocs-fr
